include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude: ["**/*.g.dart", "lib/generated/**", "**/*.chopper.dart"]
  errors:
    asset_does_not_exist: ignore
    todo: ignore

linter:
  rules:
    always_use_package_imports: true
    avoid_renaming_method_parameters: false
    always_declare_return_types: true
    sized_box_for_whitespace: true
    avoid_multiple_declarations_per_line: true
    prefer_final_in_for_each: true
    unnecessary_lambdas: true
    avoid_print: true

    require_trailing_commas: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true
    prefer_single_quotes: true
    depend_on_referenced_packages: true
    omit_local_variable_types: true
    no_leading_underscores_for_local_identifiers: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    avoid_function_literals_in_foreach_calls: true
    prefer_foreach: true
    prefer_for_elements_to_map_fromIterable: true
    unnecessary_to_list_in_spreads: true
    use_super_parameters: true
    noop_primitive_operations: true
    directives_ordering: true
    cascade_invocations: true
