name: Unit tests - off emulator

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Use FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm-config-action

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install app dependencies
        run: flutter pub get
      - name: Analyze files
        run: flutter analyze
      - name: Verify formatting
        run: dart format --line-length 120 --output=none --set-exit-if-changed .

      - name: Run unit tests directly with flutter test
        run: flutter test tests
