name: Unit tests - off emulator
env:
  FLUTTER_VERSION: '3.7.3'

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install app dependencies
        run: flutter pub get
      - name: Analyze files
        run: flutter analyze
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Run unit tests directly with flutter test
        run: flutter test test --coverage

      - name: Upload unit tests coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
